package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'GenerateDoc'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("GenerateDoc")) {
    params {
        expect {
            password("env.GH_PAGES_TOKEN", "credentialsJSON:REMPLACER-PAR-LE-TOKEN-CHIFFRE")
        }
        update {
            password("env.GH_PAGES_TOKEN", "credentialsJSON:ffdd292f-4e06-4799-a131-f7d8695583e6")
        }
    }
}
