package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.triggers.VcsTrigger
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'GenerateDoc'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("GenerateDoc")) {
    triggers {
        val trigger1 = find<VcsTrigger> {
            vcs {
                triggerRules = "+:Writerside/**"
                branchFilter = "+:refs/heads/main"
            }
        }
        trigger1.apply {
            branchFilter = "+:<default>"

        }
    }
}
