package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'PublishPackages'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("PublishPackages")) {
    params {
        expect {
            password("env.GH_PACKAGES_TOKEN", "credentialsJSON:REMPLACER-PAR-LE-TOKEN-CHIFFRE")
        }
        update {
            password("env.GH_PACKAGES_TOKEN", "credentialsJSON:00b7d8c6-e92f-42c2-b132-7d7fc6ba194b")
        }
    }
}
