package ktordiscord.core

import ktordiscord.builders.DiscordMessageBuilder
import ktordiscord.builders.embed
import ktordiscord.components.ActionRow
import ktordiscord.components.Button
import ktordiscord.components.Embed
import ktordiscord.components.MessageComponent
import ktordiscord.components.MessagePayload
import ktordiscord.components.enums.ButtonStyle
import java.util.UUID

/** Max number of components Discord allows on a single action row. */
private const val MAX_COMPONENTS_PER_ROW = 5

/** Ephemeral message flag (`1 << 6`): the response is only visible to the invoking user. */
private const val EPHEMERAL_FLAG = 1 shl 6

/**
 * DSL scope building the [MessagePayload] of an interaction response. Mirrors the `sendMessage { }`
 * fields (content, embeds…) and adds interactive components: [button] returns a [ButtonHandle] whose
 * [ButtonHandle.click] attaches the click callback inline.
 */
@DiscordMessageBuilder
class ResponseScope internal constructor(private val client: DiscordClient) {
    private val payload = MessagePayload()

    var content: String?
        get() = payload.content
        set(value) {
            payload.content = value
        }

    var tts: Boolean
        get() = payload.tts
        set(value) {
            payload.tts = value
        }

    /** Raw message flags bitfield. Prefer [ephemeral] for the common ephemeral case. */
    var flags: Int?
        get() = payload.flags
        set(value) {
            payload.flags = value
        }

    /** Mark the response ephemeral (only the invoking user sees it). */
    fun ephemeral() {
        payload.flags = (payload.flags ?: 0) or EPHEMERAL_FLAG
    }

    /** Add an embed to the response (delegates to the shared `MessagePayload.embed { }` builder). */
    fun embed(init: Embed.() -> Unit) = payload.embed(init)

    /**
     * Add a button to the response and return a handle to bind its click callback.
     *
     * @param label the button text.
     * @param customId an explicit id (e.g. for a persistent button); auto-generated by
     *   [ButtonHandle.click] when omitted.
     */
    fun button(
        label: String? = null,
        customId: String? = null,
        init: (Button.() -> Unit)? = null,
    ): ButtonHandle {
        val button = Button(label = label, customId = customId).apply { init?.invoke(this) }
        addComponent(button)
        return ButtonHandle(button, client)
    }

    // Discord requires interactive components inside an action row. Fill the last row up to
    // MAX_COMPONENTS_PER_ROW, then start a new one.
    private fun addComponent(component: MessageComponent) {
        val components = payload.components
            ?: mutableListOf<MessageComponent>().also { payload.components = it }
        val lastRow = components.lastOrNull() as? ActionRow
        if (lastRow != null && lastRow.components.size < MAX_COMPONENTS_PER_ROW) {
            components[components.lastIndex] = ActionRow(lastRow.components + component)
        } else {
            components.add(ActionRow(listOf(component)))
        }
    }

    internal fun build(): MessagePayload = payload
}

/**
 * Handle returned by [ResponseScope.button]. Its [click] binds the callback fired when the button
 * is pressed, without registering anything at the [DiscordClient] level.
 */
class ButtonHandle internal constructor(
    private val button: Button,
    private val client: DiscordClient,
) {
    /**
     * Register the callback run when this button is clicked. Generates a `custom_id` for the button
     * if it has none. No-op for [ButtonStyle.LINK] buttons, which navigate to a url and emit no
     * interaction.
     */
    fun click(handler: ComponentHandler): ButtonHandle {
        if (button.style == ButtonStyle.LINK) {
            client.interactionLogger.warn { "click {} ignored: a LINK button emits no interaction" }
            return this
        }
        val id = button.customId ?: UUID.randomUUID().toString().also { button.customId = it }
        client.registerComponentHandler(id, handler)
        return this
    }
}
